import java.util.Scanner;

public class Bai2 {
    public static void main (String[] args){
        Scanner scanner = new Scanner(System.in);

        // Khởi tạo mảng
        System.out.print("Nhập kích thước của mảng: ");
        int size = scanner.nextInt();
        int[] array = new int[size];

        System.out.println("Nhập các phần tử cho mảng:");
        for (int i = 0; i < size; i++) {
            System.out.print("Giá trị thứ " + (i + 1) + ": ");
            array[i] = scanner.nextInt();
        }

        // Tính tổng
        int sum = 0;
        for (int value : array) {
            sum += value;
        }

        // Đầu ra
        System.out.println("Tổng các phần tử trong mảng: " + sum);
    }
}
